spring.application.name=EcommerceProductService
server.port=8081

#FakeStore Configuration
fakestore.api.url = https://fakestoreapi.com
fakestore.api.path.product=/products

#Database Properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.show-sql=true
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/EcommerceProductService
spring.datasource.username=root
spring.datasource.password=root

#OAuth2.0 url
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://localhost:8888


server.ssl.enabled=true
server.ssl.key-store=classpath:productService.p12
server.ssl.key-store-password=productservice
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=productservice

