spring.application.name=serviceDiscovery

server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#eureka.client.service-url.defaultZone= http://localhost:8761/eureka

# Enable SSL
server.ssl.enabled=true

# Keystore config
server.ssl.key-store=classpath:eCommerceApplication.p12
server.ssl.key-store-password=eCommerceApplication
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=eCommerceApplication