spring.application.name=EcommerceUserService
#server.port=8082

#Database Properties
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.properties.hibernate.show-sql=true
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:mysql://localhost:3306/EcommerceUserService
#spring.datasource.username=root
#spring.datasource.password=root

#token.expiry=3


#jks configuration
#jks.key.file=userService.jks
#jks.password=userService
#jks.alias=userService


logging.level.org.springframework=trace

#SSL Configuration
#server.ssl.enabled=true
#server.ssl.key-store=classpath:eCommerceApplication.p12
#server.ssl.key-store-password=eCommerceApplication
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=eCommerceApplication

#Config server configuration
spring.config.import=optional:configserver:http://localhost:8080
spring.cloud.config.username={cipher}5a0e4ddac5c7e8d2078fae3eac2e8a528ac7573e6fdcde9cd60b4632b4a6d918
spring.cloud.config.password={cipher}3ad658b6644ead352db821608da694a6f6632a98a7fbf72591cb6ef99eb683b2
encrypt.key=sK1rk2mv83nVsk3B

#Eureka client config
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone= https://localhost:8761/eureka