spring.application.name=configurationServer

# Git Repo Configuration
#spring.cloud.config.server.git.uri=https://github.com/mayankchandrol201997/config-repo
#spring.cloud.config.server.git.clone-on-start=true

# Optional
#spring.cloud.config.server.git.default-label=master


#Database Properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.show-sql=true
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/configurationServer
spring.datasource.username=root
spring.datasource.password=root

spring.flyway.enabled=true

# Basic Auth credentials
spring.security.user.name=admin
spring.security.user.password=admin123

encrypt.key=sK1rk2mv83nVsk3B

logging.level.org.springframework=trace
